### PR TITLE
[GCI][Task][website] Add a page with the public github activity #26

### LINKED ISSUE #26: [feed] Improve github activity feed
We need to improve the github activity feed just added in #24 a bit more so we can start showing it to visitors of the website.

- convert emoji characters to emoji icons
- find a way to fix URLs which break on new lines
- convert mentions (eg: `@username`) to links to the respective github profiles
- show the github open pull request icon on opened pull requests (you can reuse the  github SVG)
- show the github merged pull-request icon (purple icon) on merged pull requests  (you can reuse the SVG)
- show the open issue icon on opened issues  (you can reuse the github SVG)
- show the closed issue icon on closed issues  (you can reuse the github SVG)
- convert the logic in a way that allows creating the activity feed by calling a function
  - make the function accept a parameter that specifies the initial number of items loaded from the github API
  - make the function accept a parameter that specifies if an optional load more button should be displayed or not, when visible this load button should allow loading more items from the github API which are added to the bottom
- ignore comments from coveralls
- show the latest 5 items in the homepage and instead of the load more show a button that points to the activity page where we will show the full activity (this button should be done directly in HTML instead of javascript)

### PR DESCRIPTION
**Pull request by unsuitable001**
Live Preview Link : https://unsuitable001.github.io/OpenWISP-Website/gh-activity
Task Instance Link : https://codein.withgoogle.com/dashboard/task-instances/4775796238450688/
@nemesisdesign @atb00ker.
Fixes #26

### CODE REVIEW

**Comment by atb00ker** [comment]
It looks like you are using GitHub's user interface to interact with repository and upload changes.
At some point you'll need to learn using Git from command line; i suggest try out the tutorials for the same. (There is even a task for learning Git! ) :smile:

**Comment by unsuitable001** [comment]
> It looks like you are using GitHub's user interface to interact with repository and upload changes.
> At some point you'll need to learn using Git from command line; i suggest try out the tutorials for the same. (There is even a task for learning Git! ) smile

Yep. I'm using github right now. I'll learn terminal interface. I like the white on black interface :)

**Comment by atb00ker** [comment]
Okay. To begin with, squash all the commits and make 1 commit as per the guidelines here: http://openwisp.io/docs/developer/contributing.html?highlight=commit#commit-message-style-guidelines

**Comment by unsuitable001** [comment]
@atb00ker @nemesisdesign can I get any insights about the page? Should I continue improving it?

**Comment by atb00ker** [comment]
@unsuitable001 
You can abandon it, it's good word and this pull request has been approved in GCI system.
If we want, we can pick it up from here later. For now, you can take up other tasks on GCI. :smile:

**Comment by unsuitable001** [comment]
I'll love to do improvements here. But, will focus more on other tasks for now. I'll commit it after the end of GCI.

**Pull request closed without merging**
