### PR TITLE
[thecode.html] Added RubyMine logo in #3

### LINKED ISSUE #3: Add image for RubyMine IDE
http://openwisp.org/thecode.html

Under Developed with, the intended image doesn't show up. Also add the name of the IDE to the alternate text.

### PR DESCRIPTION
**Pull request by thejwzhang**
Simple fix of removing a broken link to the RubyMine logo and adding in the image.
Fixes #3 

It seems as if any code editor I try to use does the same thing: change unnecessary lines. I have tried Sublime, Brackets, and the inline Github code editor.

Screenshots are attached below. The one with the logo is the one with the changes.
new
old

### CODE REVIEW

**Comment by thejwzhang** [comment]
Upon further inspection, the actual website (at openwisp.org) is very different from the website given by the code here on Github.

**Comment by HargovindArora** [comment]
@thejwzhang The image size looks inappropriate, it should be something more compact. Please have a look @nemesisdesign! 

And regarding the unnecessary changes that are occurring can you please see what format are you using like 'LF' or 'CRLF' and which charset also 'UTF-8' or any other in your code editor? Below is the screenshot of my editor settings!

image

**Comment by thejwzhang** [comment]
image
I've updated the logo to make it less massive and out of place.

**Comment by HargovindArora** [comment]
@thejwzhang Have looked upon the editor settings that I have proposed in the above comment!

**Pull request closed without merging**
